/**
 * PHIL_FILENAME — транслитерация имён философов для имён файлов экспорта.
 * Дословный порт из philosynth.html (~17325–17432), порядок исходника.
 * Используется getDocFilename() (server/services/export/filename.ts).
 */

export const PHIL_FILENAME: Readonly<Record<string, string>> = {
  "Пифагор": "Pythagoras",
  "Гераклит": "Heraclitus",
  "Парменид": "Parmenides",
  "Демокрит": "Democritus",
  "Сократ": "Socrates",
  "Платон": "Plato",
  "Аристотель": "Aristotle",
  "Эпикур": "Epicurus",
  "Зенон Стоик": "Zeno-Stoic",
  "Секст Эмпирик": "Sextus-Empiricus",
  "Марк Аврелий": "Aurelius",
  "Плотин": "Plotinus",
  "Августин": "Augustine",
  "Боэций": "Boethius",
  "Аль-Фараби": "Al-Farabi",
  "Авиценна": "Avicenna",
  "Ансельм Кентерберийский": "Anselm",
  "Аверроэс": "Averroes",
  "Маймонид": "Maimonides",
  "Фома Аквинский": "Aquinas",
  "Дунс Скот": "Scotus",
  "Уильям Оккам": "Ockham",
  "Николай Кузанский": "Cusanus",
  "Макиавелли": "Machiavelli",
  "Фрэнсис Бэкон": "Bacon",
  "Декарт": "Descartes",
  "Гоббс": "Hobbes",
  "Спиноза": "Spinoza",
  "Локк": "Locke",
  "Лейбниц": "Leibniz",
  "Беркли": "Berkeley",
  "Монтескьё": "Montesquieu",
  "Юм": "Hume",
  "Руссо": "Rousseau",
  "Кант": "Kant",
  "Фихте": "Fichte",
  "Шеллинг": "Schelling",
  "Гегель": "Hegel",
  "Шопенгауэр": "Schopenhauer",
  "Фейербах": "Feuerbach",
  "Огюст Конт": "Comte",
  "Кьеркегор": "Kierkegaard",
  "Маркс": "Marx",
  "Милль": "Mill",
  "Дильтей": "Dilthey",
  "Брентано": "Brentano",
  "Пирс": "Peirce",
  "Ницше": "Nietzsche",
  "Фреге": "Frege",
  "Мейнонг": "Meinong",
  "Джеймс": "James",
  "Фрейд": "Freud",
  "Юнг": "Jung",
  "Гуссерль": "Husserl",
  "Бергсон": "Bergson",
  "Дьюи": "Dewey",
  "Уайтхед": "Whitehead",
  "Рассел": "Russell",
  "Кассирер": "Cassirer",
  "Витгенштейн": "Wittgenstein",
  "Хайдеггер": "Heidegger",
  "Ясперс": "Jaspers",
  "Карнап": "Carnap",
  "Батай": "Bataille",
  "Марсель": "Marcel",
  "Гадамер": "Gadamer",
  "Лакан": "Lacan",
  "Адорно": "Adorno",
  "Хоркхаймер": "Horkheimer",
  "Маркузе": "Marcuse",
  "Сартр": "Sartre",
  "Арендт": "Arendt",
  "Левинас": "Levinas",
  "Мерло-Понти": "Merleau-Ponty",
  "Куайн": "Quine",
  "Поппер": "Popper",
  "Остин": "Austin",
  "Райл": "Ryle",
  "Кун": "Kuhn",
  "Лакатос": "Lakatos",
  "Дэвидсон": "Davidson",
  "Крипке": "Kripke",
  "Камю": "Camus",
  "Делёз": "Deleuze",
  "Фуко": "Foucault",
  "Деррида": "Derrida",
  "Рикёр": "Ricoeur",
  "Бодрийяр": "Baudrillard",
  "Лиотар": "Lyotard",
  "Хомский": "Chomsky",
  "Рорти": "Rorty",
  "Хабермас": "Habermas",
  "Ролз": "Rawls",
  "Нозик": "Nozick",
  "Жижек": "Zizek",
  "Конфуций": "Confucius",
  "Лао-цзы": "Laozi",
  "Нагарджуна": "Nagarjuna",
  "Шанкара": "Shankara",
  "Чаадаев": "Chaadaev",
  "Соловьёв": "Solovyov",
  "Лосский": "Lossky",
  "Бердяев": "Berdyaev",
  "Флоренский": "Florensky",
  "Шестов": "Shestov",
  "Лосев": "Losev",
} as const;
